name: CI

on:
  pull_request:
  merge_group:

permissions:
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verification:
    name: Verification
    uses: ./.github/workflows/reusable-verification.yml
    secrets: inherit

  success:
    needs:
      - verification
    name: Success
    runs-on: ubuntu-latest
    steps:
      - name: Echo Success
        run: |
          echo "::notice Success!"
